common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:
  host: '127.0.0.1'

development:
  <<: *common
  database: copypaste_development

test:
  <<: *common
  database: copypaste_test

production:
  <<: *common
  database: copypaste_production
